export {
  createDatadogConnector,
  type DatadogConnector,
  type DatadogConnectorConfig,
  type DatadogMetric,
  type DatadogMetricPoint,
  type DatadogMetricSeries,
  type DatadogMonitor,
  type DatadogMonitorOptions,
  type DatadogMonitorThresholds,
  type DatadogUser,
  type DatadogDashboard,
  type DatadogWidget,
  type DatadogHost,
  type DatadogEvent,
  type DatadogServiceLevelObjective,
  type DatadogSLOStatus,
  type DatadogIncident,
  type DatadogLogQuery,
  type DatadogLog,
  type MetricType,
  type MonitorState,
  type MonitorType,
} from "./client.js";
